### PR TITLE
mobile boxes: color coding

### PR DESCRIPTION
**Pull request by noerw**
applies color coding for boxes throughout the application based on the box exposure type and its activity.

- box markers
- circle marker rings
- dashboard background

shall we keep the special rocket icon for mobile boxes?

### CODE REVIEW

**Comment by noerw** [comment]
legend
`^---` requires css fix, couldn't do it

dashboard
`^---` no color grading based on activity, because `api/users/me/boxes` does not return populated `sensors[].lastMeasurement` fields

**Comment by ubergesundheit** [comment]
@noerw I'll see if I can add population of the `lastmeasurements` for the `users/me/boxes` call.

**Comment by ubergesundheit** [comment]
https://github.com/sensebox/openSenseMap-API/commit/68c9b2ab9289441f7945247a7c657d8127c825e1

**Comment by ubergesundheit** [comment]
Whats the status of this pull request? Is it ready?

**Comment by noerw** [comment]
Apart from the vertical overflow in the legend, this should be good now from my side.
@mpfeil maybe you could look for a way to make the legend annotation work?

**Comment by mpfeil** [comment]
I can do it on the 20th of November. 
@ubergesundheit @noerw what do you think about coloring the `luftdaten.info` boxes in a different color and mention them in the legend?

**Comment by ubergesundheit** [comment]
Another idea: Color the "official" senseBox Kits differently than all other boxes.

**Comment by mpfeil** [comment]
What do you think about this style of legend? @noerw @ubergesundheit @robarto 

legend

**Comment by ubergesundheit** [comment]
Will the color of the markers also be continious or will they stay as they currently are (3 different colors)? Looks good, but it removes the easy distinction between active and inactive stations.

I think it would be better, if there would be only just two "freshnes" categories. Like "Active in the last hour" and "not active in the last hour".

**Comment by mpfeil** [comment]
Right now the color of the markers stay as they are but I am up for discussion.

"Active in the last hour" is definitely to short.
But we can change it to two "freshness" categories.

**Comment by noerw** [comment]
@mpfeil I like the concept.
I think `grey` should be more prominent in the the color bars though, right now the grey markers are not really represented in the color-bar.
Also, I would set a blue/green bg-color for `mobile` and `stationaer`

**Comment by mpfeil** [comment]
Thanks for your feedback @noerw 

This is the new one
legend_new

**Comment by ubergesundheit** [comment]
What happens when sensors of mobile boxes are selected? Is there still the additional legend?

**Comment by mpfeil** [comment]
Haven't changed the mobile legend. But there is also no mobile box to test.

**Pull request merged**
