### PR TITLE
Add autocomplete="off" to wifi credential inputs

### PR DESCRIPTION
**Pull request by ubergesundheit**
Possible fix for #295

### CODE REVIEW

**Comment by mpfeil** [comment]
I tried it and it is not working in Chrome (`73.0.3683.86 (Offizieller Build) (64-Bit)`) on Windows (`10.0.17134 Build 17134`).
autocomplete.

I also tried `autocomplete="off"` on the wifi credentials fields in the editing section and it has no effect. Found different approches but none was working.

Does `autocomplete="off"` has any effect on your OS?

**Comment by ubergesundheit** [comment]
oh you're right, I wrote the change without testing from memory. Didn't know Chrome is such a sucker for ignoring `autocomplete="off"`

**Comment by noerw** [comment]
did you try giving it a distinct name attribute? and I heard adding hidden user/password fields to the form diables autocomplete on the visible fields. everything else is difficult as password managers ignore the autocomplete attribute

**Comment by mpfeil** [comment]
Haven`t tried distinct name attributes.
Hidden user/password fields are ignored by Chrome.

I added something like the following to the form:
```
<input type="text" style="display:none;">
<input type="password" style="display:none;">
```

Maybe you can give it a try.

**Pull request closed without merging**
