### PR TITLE
Fixing the build process

### PR DESCRIPTION
**Pull request by tiefpunkt**
I was facing some issues building the OSEM application stack (see https://twitter.com/tiefpunkt/status/1026592386703650821 and https://gist.github.com/tiefpunkt/a0e04213d74a7edc248a3635bf01004b for reference), so here's the first part of my fix.

### Fix or Enhancement and description?
Fix.
#### Grunt build
First off to the grunt build. I received the following error when building the project:
```
Running "languages" task
Fatal error: ENOENT: no such file or directory, scandir '.tmp/translations/'
```
This was fixed with adding the copyTranslations task. 

#### Docker build
Then the build process of the Docker container was adjusted. README.md mentions for building you just have to run `docker build` with the proper variables set, but this was not the case. The build required to have the whole npm/bower/grunt dance already completed, and the variables didn't do anything in the docker build process anymore. I've added a build stage to the container build that takes care of the actual building of the application. Now I used the `digitallyseamless/nodejs-bower-grunt` image for this, I hope that works for everyone.

### Environment
- OS: macOS 10.13.3
- Browser & Version: -irrelevant-

### CODE REVIEW

**Comment by ubergesundheit** [comment]
Thanks for your contribution!

The current Dockerfile was written long ago (when mulitstage wasn't so easy) to just copy in the build artifacts from a CI run on travis.

We will test this out and then @mpfeil will merge this eventually

**Comment by ubergesundheit** [comment]
One request though: 
Merging this would double the time spent in CI because now everything gets built twice. You could either:

- Modify CI configuration to only build everything once (in the container image build process you defined)
- Create a `Dockerfile.CI` which retains the old behaviour for building in CI. Make sure you also instruct CI to use this new file.

**Comment by ubergesundheit** [comment]
Hey @tiefpunkt sorry for closing this. If you want, you could recreate it with the changes in master..

**Comment by tiefpunkt** [comment]
@ubergesundheit I think I'll pass, I'm not using this anymore. If it's still of any use, I can leave that branch up for reference, otherwise I'll likely just delete it.

**Comment by ubergesundheit** [comment]
Very well. IMO it should be fine if you delete the branch :) Thanks again

**Pull request closed without merging**
