### PR TITLE
adding Plantower PMS7003/5003/3003/1003 particle matter sensors for luftdaten.info

### PR DESCRIPTION
**Pull request by Adorfer**

### CODE REVIEW

**Comment by Adorfer** [comment]
Modified as requested by @ubergesundheit in https://github.com/sensebox/openSenseMap-API/pull/121#issuecomment-339398611

**Comment by Adorfer** [comment]
fix numbering/order of PMS radio buttons

**Comment by ubergesundheit** [comment]
Thanks again for your pull request! 

First thing: I would appreciate if you could change the pull request to merge into `development`. You could change the parent of your [first commit](https://github.com/Adorfer/openSenseMap/commit/9f31630c93d1911be38c3bd27a0b3c16a536e1b4) to the [last commit of the development branch](https://github.com/sensebox/openSenseMap/commit/c5a46ccfcb5db73e2c1a5b083de85ec7b8296592) or close this one and apply your changes starting from the development branch.
Thanks!

Also could you please make the following changes before I can merge:

In the `register.html` view:
Change the Labels to `Luftdaten.info Feinstaubsensor ($Feinstaubsensormodel)`. Add round parentheses around the sensor model and do not write out the vendor (`PMS7003` instead of `Plantower PMS7003`)

In `app/scripts/controllers/register.js` in line [377](https://github.com/sensebox/openSenseMap/blob/master/app/scripts/controllers/register.js#L377) replace the watcher with
```js
    $scope.$watch('register.modelSelected.id', function(newValue) {
      if (newValue.indexOf('home') === 0) {
        vm.modelSelected.name = 'senseBox Home ' + newValue.substring(4);
        vm.sensorSetup = vm.modelSelected.id;

        vm.invalidHardware = false;

        return;
      }

      if (newValue.indexOf('luftdaten') === 0) {
        vm.sensorSetup = vm.modelSelected.id;
        vm.extensions.feinstaub.id = '';

        var nameParts = newValue.split('_');

        var name = 'Luftdaten.info Feinstaubsensor (' + nameParts[1].toUpperCase() + ')';

        if (!nameParts[2]) {
          name += ' ohne Temperatur-/Feuchtesensor';
        } else {
          name += ' mit ' + nameParts[2].toUpperCase();
        }
        vm.modelSelected.name = name;

        vm.invalidHardware = false;

        return;
      }

      if (newValue === 'custom') {
        vm.sensorSetup = '';
        vm.extensions.feinstaub.id = '';

        vm.invalidHardware = false;

        return;
      }

      vm.modelSelected.name = false;
    });
```

**Comment by ubergesundheit** [comment]
For the second change in the javascript controller, please wait just for now.

**Comment by ubergesundheit** [comment]
ok, nevermind. It should work.

**Comment by Adorfer** [comment]
sorry, i am lost now. 
Please do this yourself, i am totally not used to website-building. So whatever i will do here will certainly be some kind of sub-standard stuff and cause for your more difficulties to correct than as if you do it yourself.

**Comment by ubergesundheit** [comment]
Ok. No Problem. I have added your commits to the `development` branch. 

Thanks again for your contribution! I'll close this pull request now. The changes are already up on osem.vo1d.space and will be merged to `master` soon.

**Pull request closed without merging**
